
import type { VercelRequest, VercelResponse } from '@vercel/node';
import PDFDocument from 'pdfkit';

function unauthorized(res: VercelResponse) { return res.status(401).json({ error: 'Unauthorized' }); }

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const hdr = req.headers['x-tbm-auth'] as string | undefined;
  if (!hdr) return unauthorized(res);
  const [user, pass] = Buffer.from(hdr, 'base64').toString('utf8').split(':');
  if (user !== process.env.TBM_LOGIN_USER || pass !== process.env.TBM_LOGIN_PASS) return unauthorized(res);

  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const data = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="TBM_Supplement.pdf"');

  const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
  doc.pipe(res);

  doc.fillColor('#000').fontSize(18).text('TBM Supplementing Machine – Internal Report', { align: 'left' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#555').text('Protecting policyholders • Generated by TBM Public Adjusters');
  doc.moveDown();

  doc.fillColor('#B00020').fontSize(14).text('Findings', { underline: true });
  doc.fillColor('#111').fontSize(10).moveDown(0.3);
  doc.text(JSON.stringify(data?.findings ?? [], null, 2), { lineGap: 2 });

  doc.moveDown();
  doc.fillColor('#B00020').fontSize(14).text('Building Code & Manufacturer Citations', { underline: true });
  doc.fillColor('#111').fontSize(10).moveDown(0.3);
  doc.text(JSON.stringify(data?.code_citations ?? [], null, 2), { lineGap: 2 });

  doc.moveDown();
  doc.fillColor('#B00020').fontSize(14).text('Price Deltas', { underline: true });
  doc.fillColor('#111').fontSize(10).moveDown(0.3);
  doc.text(JSON.stringify(data?.price_deltas ?? [], null, 2), { lineGap: 2 });

  doc.moveDown();
  doc.fillColor('#B00020').fontSize(14).text('Draft Supplement Letter', { underline: true });
  doc.fillColor('#111').fontSize(10).moveDown(0.3);
  doc.text(String(data?.supplement_letter ?? ''), { lineGap: 3 });

  doc.end();
}
